kind: Service
apiVersion: v1
metadata:
  name: contosouniversityapp
spec:
  selector:
    app: contosouniversityapp
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosouniversityapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contosouniversityapp
        tier: frontend
        track: stable
    spec:
      containers:
        - name: contosouniversityapp
          image: "leadroregistry.azurecr.io/contosouniversity.web:BuildNumber"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: URLAPI
              value: "http://contosouniversityapi:9000/"
      imagePullSecrets:
        - name: acr