version: '3.4'

services:
  
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: contosouniversitydb
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"

  contosouniversity.webapplication:
    image: ${DOCKER_REGISTRY}contosouniversity-web
    container_name: contosouniversitywebapp
    build:
      context: .
      dockerfile: ContosoUniversity.WebApplication/Dockerfile
    depends_on:
      - contosouniversity.api
    ports:
      - "7171:80"
    environment:
      URLAPI: http://contosouniversitywebapi:80/

  contosouniversity.api:
    image: ${DOCKER_REGISTRY}contosouniversity-api
    container_name: contosouniversitywebapi
    build:
      context: .
      dockerfile: ContosoUniversity.API/Dockerfile
    depends_on:
      - db
    ports:
      - "7272:80"
    environment:
      DBHOST: db
      DBNAME: ContosoSchoolContext
      DBPORT: 1433
      DBUSERNAME: sa
      DBPASSWORD: P@ssw0rd