# https://learn.microsoft.com/en-us/azure/container-instances/container-instances-github-action?tabs=userlevel

name: ContosoUniversity-Docker

on:
  workflow_dispatch:
  
env:
  IMAGE_NAME_API: contosouniversity.api
  IMAGE_NAME_APP: contosouniversity.webapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/ContosoUniversity.API
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME_API }}:${{ GITHUB.RUN_NUMBER }}
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME_API }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push WEBAPP Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/ContosoUniversity.WebApplication
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME_APP }}:${{ GITHUB.RUN_NUMBER }}
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME_APP }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
