name: git-mirror

on:
  workflow_dispatch:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: | 
          pwd
          ls -R
      
      - run: git remote -v

      - run: git remote set-url origin https://user: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@github.com/lsprado/teste-mirror.git

      - run: git remote -v

      - run: git push --force
      
      #- name: Run a git mirror
      #  run: |
      #    git clone --bare https://user:${{ secrets.GH_FROM }}@github.com/contoso-projects/contoso-university.git
      #    cd contoso-university
      #    git -c http.sslVerify=false push --mirror https://user:${{ secrets.GH_TO }}@github.com/lsprado/teste-mirror.git
